Do not Import-Package: which were Export-Package: here
Even though
http://blog.osgi.org/2007/04/importance-of-exporting-nd-importing.html
recommends this (and that's why the openHAB archetype has it like this),
but does say that in this case it would be OK not do do (because we
should never have any other bundle in this same package namespace..), it
caused exceptions on (first) load of this bundle, in openHAB's Karaf on
Equinox:

org.osgi.framework.BundleException: Could not resolve module:
org.openhab.binding.roverrobot [10]
  Unresolved requirement: Import-Package: org.openhab.binding.roverrobot

    at
org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at
org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at
org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
    at
org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
    at
org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:509)[8:org.apache.felix.fileinstall:3.5.0]
    at
org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
    at
org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]